# Generated by Django 3.0.5 on 2020-07-26 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0009_property_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='categroy',
            new_name='category',
        ),
    ]
